apiVersion: v1
kind: Service
metadata:
  name: weather-agent
  namespace: agents
  labels:
    app.kubernetes.io/name: weather-agent
spec:
  selector:
    app.kubernetes.io/name: weather-agent
  ports:
    - port: 9000
      targetPort: a2a
      name: a2a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-agent
  namespace: agents
  labels:
    app.kubernetes.io/name: weather-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weather-agent
    spec:
      serviceAccountName: weather-agent
      containers:
        - name: weather-agent
          image: ${ECR_REPO_WEATHER_AGENT_URI}:latest
          ports:
            - containerPort: 9000
              name: a2a
          env:
          - name: WEATHER_MCP_URL
            value: "http://weather-mcp.mcp-servers:8080/mcp"
          - name: A2A_URL
            value: "http://weather-agent.agents:9000"
          command: ["agent-a2a-server"]
          livenessProbe:
            tcpSocket:
              port: 9000
          readinessProbe:
            httpGet:
              path: /.well-known/agent-card.json
              port: 9000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-agent
  namespace: agents
  labels:
    app.kubernetes.io/name: weather-agent
